### ISSUE TITLE
'yarn-upgrade-all' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Deilan** [tylerlong/yarn-upgrade-all#1]
Trying to use after install:
> 'yarn-upgrade-all' is not recognized as an internal or external command, operable program or batch file.

**Comment by tylerlong** [comment]
Install it globally: `yarn global add yarn-upgrade-all`.

If you install it locally, you need to `./node_modules/.bin/yarn-upgrade-all`.

**Comment by Deilan** [comment]
@tylerlong I did install it globally. It doesn't work after that.

![image](https://user-images.githubusercontent.com/4777512/29016625-d690acb8-7b5b-11e7-99ff-0465ea616d79.png)

**Comment by tylerlong** [comment]
@Deilan  I don't use Windows and I didn't test it on windows.

I guess you will have issues with all node command line libraries, not only `yarn-upgrade-all`.

Please read this thread: https://stackoverflow.com/questions/9587665/nodejs-cannot-find-installed-module-on-windows

Let me know if it works.

**Comment by Deilan** [comment]
@tylerlong Nope, I don't have any problems with any of popular and ubiquitous npm modules globally installed on Windows. Moreover, I didn't have to make any additional actions upon installing them to make them work right after install. `grunt`, `gulp`, `yarn`, `tsc`, `tslint` are just some of them and they work quite well.

**Comment by tylerlong** [comment]
I am not sure I have fixed the issue but I've released a new version. Could you please have a try?

Here is the change: https://github.com/tylerlong/yarn-upgrade-all/commit/9f03841052bed506f50d34a56f47b23bbbcac31d

I think changing

```json
"bin": "index.js"
```

to

```json
"bin": {
  "yarn-upgrade-all": "./index.js"
},
```

might fix the issue.

**Comment by tylerlong** [comment]
I just tried and it worked:

```
PS C:\Users\tyler\AppData\Local\Yarn\bin> npm install -g yarn-upgrade-all
C:\Users\tyler\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs\yarn-upgrade-all -> C:\Users\tyler\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs\node_modules\yarn-upgrade-all\index.js
C:\Users\tyler\AppData\Local\scoop\apps\nodejs\6.7.0\nodejs
`-- yarn-upgrade-all@0.1.6
  `-- chalk@2.1.0
    +-- ansi-styles@3.2.0
    | `-- color-convert@1.9.0
    |   `-- color-name@1.1.3
    +-- escape-string-regexp@1.0.5
    `-- supports-color@4.2.1
      `-- has-flag@2.0.0

PS C:\Users\tyler\AppData\Local\Yarn\bin> yarn-upgrade-all.cmd
Error: Cannot find package.json file in the current directory
PS C:\Users\tyler\AppData\Local\Yarn\bin>
```


However `yarn global add ...` won't work which I believe is yarn's bug. There is an open issue: https://github.com/yarnpkg/yarn/issues/2224
