### ISSUE TITLE
feat: passing options to yarn 

### ISSUE THREAD

**Issue by jjangga0214** [tylerlong/yarn-upgrade-all#17]
Hi!

Sometimes, it might be needed to pass a specific option to `yarn add`.

For example, I want to execute `yarn add -D --ignore-workspace-root-check <package>`. 

In this case, currently there is no way to pass `--ignore-workspace-root-check` option to `yarn-upgrade-all`.

How about allowing it?

I think a solution like `yarn-upgrade-all --foo-option --bar-option` would be good.

How do you think?

Thanks!

**Comment by dhlavaty** [comment]
+1 and support for yarn workspaces would be cool

**Comment by tylerlong** [comment]
It is now supported. You may pass any options to yarn:

```
yarn yarn-upgrade-all --my-option
```

For yarn workspaces, it is possible to update all by:

```
yarn yarn-upgrade-all -W
yarn workspaces run yarn-upgrade-all
yarn install
```
