### ISSUE TITLE
Package should remove all packages and install all with 2 commands

### ISSUE THREAD

**Issue by vsorrokin** [tylerlong/yarn-upgrade-all#2]
yarn remove one two three four
yarn add one two three fours

This works much faster than remove and add every package in sequence

**Comment by tylerlong** [comment]
Being fast is not among the goals of this project.  

`yarn upgrade --latest` is the fastest, but most of the time it doesn't work for me.

It processes the packages one by one so you can track the progress, and if one of the packages fails to install you can easily know which one it is and fix it manually easily. 

Take 

```
yarn remove one two three four
yarn add one two three fours
```

for example, if it fails to install package `one`. Not only you need to fix package `one` manually but also you lost `two`, `three` & `four` from your dependencies list.

**Comment by Roms1383** [comment]
Why not just use `npm view <package> version` for each package, replace package's version with it in the `package.json` (keeping npm semver range like `^`, `~`, etc) and re-run `yarn install` / `npm install` ?

IMHO It should be way faster and accurate.

And it would prevent inconsistencies, like for example :

> I had `jest@^24.1.0`, after using  `npx yarn-upgrade-all` I ended up having `jest@^24.0.18` whereas the current latest version is `jest@^24.9.0`

**Comment by tylerlong** [comment]
> I had jest@^24.1.0, after using npx yarn-upgrade-all I ended up having jest@^24.0.18 whereas the current latest version is jest@^24.9.0

I don't understand. yarn-upgrade-all will always upgrade libraries to latest stable version. It should NEVER downgrade your libraries.

Please help me to reproduce this issue.

I do think `npm view <package> version` is a good idea.

**Comment by tylerlong** [comment]
`yarn` current doesn't have a programmatic API.

**Comment by simonwep** [comment]
@tylerlong NPM Does, yarn uses the registry of npm....

**Comment by tylerlong** [comment]
I believe the latest version is very fast.
