### ISSUE TITLE
Is there a way to access a private artifact repository?

### ISSUE THREAD

**Issue by kiranbayram** [tylerlong/yarn-upgrade-all#29]
so that we can use this tool to update our private dependencies in the company

**Comment by tylerlong** [comment]
I have no experience with private dependencies.
Basically this tool is invoking the `yarn add` command. 
It should work if `yarn add` works.

**Comment by Nantris** [comment]
@tylerlong it would need to use a syntax like this:

`yarn add --dev @scope/package-name@github:scope/package-name`

But I assume what it's doing instead is `yarn add --dev @scope/package-name` - which won't be found.
