### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by simonwep** [tylerlong/yarn-upgrade-all#6]
It takes a really long time to upgrade each package in particular. It would be a lot faster if you use [the npm-api](https://www.npmjs.com/package/npm-api) to fetch the versions, replace these in the `package.json` and run `yarn` after it.

**Comment by vesper8** [comment]
agree with the above.. currently it takes forever, I just ran it on one of my projects and it took over an hour!

**Comment by elderapo** [comment]
I don't think it's necessary to remove packages before updating them. `yarn add pkg-1 pkg-2 pkg-3 ...` should be enough.

@Edit:

```js
const packageJson = require("./package.json");
const { execSync } = require("child_process");

const allDeps = {
  ...packageJson.devDependencies,
  ...packageJson.dependencies
};

const allDepsNames = Object.keys(allDeps);

execSync(`yarn add ${allDepsNames.join(" ")}`);
```

**Comment by lropero** [comment]
..or you could use [upgradeps](https://www.npmjs.com/package/upgradeps), which checks the version prior to updating :)

**Comment by lropero** [comment]
If you want same results but fast, try [upgradeps](https://www.npmjs.com/package/upgradeps) which does parallel version querying for all packages before updating.

Disclaimer: I've built it.

**Comment by simonwep** [comment]
@lropero Lol, 15 versions spread about 26 commits 🤣 jk. nicely done :D

**Comment by lropero** [comment]
..happens :)

**Comment by tylerlong** [comment]
The issue has been discussed here: https://github.com/tylerlong/yarn-upgrade-all/issues/2#issuecomment-383852663
