### ISSUE TITLE
Doesn't handle local dependencies

### ISSUE THREAD

**Issue by danielnixon** [tylerlong/yarn-upgrade-all#8]
e.g. 

```
"dependencies": {
  "foo": "../foo"
}
```

These should probably just be ignored.

**Comment by tylerlong** [comment]
Agreed.

**Comment by tylerlong** [comment]
For now you can manually ignore it:
https://github.com/tylerlong/yarn-upgrade-all#ignore-some-packages

**Comment by tylerlong** [comment]
Make sure that it starts with `file:` and it will be ignored.

For example:

```
"dependencies": {
  "foo": "file:../foo"
}
```
